= Mock Investment API Documents
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
:sectnums:
:docinfo: shared-head

== 주가 관련
=== 현재 주가 조회
==== 성공
operation::stock-prices/success[snippets='http-request,http-response']
==== 실패
===== 유효하지 않은 코드
operation::stock-prices/fail/invalidCode[snippets='http-request,http-response']

=== 특정 기간 주가 조회
==== 최근 1주일
===== 성공
operation::stock-prices/candles/success/1w[snippets='http-request,http-response']
==== 최근 3개월
===== 성공
operation::stock-prices/candles/success/3m[snippets='http-request,http-response']
==== 최근 1년
===== 성공
operation::stock-prices/candles/success/1y[snippets='http-request,http-response']
==== 최근 5년
===== 성공
operation::stock-prices/candles/success/5y[snippets='http-request,http-response']


== 주식 주문
=== 주식 주문 요청 생성
==== 구매 요청
===== 성공
operation::stock-orders/success/buy[snippets='http-request,http-response']
==== 판매 요청
===== 성공
operation::stock-orders/success/sell[snippets='http-request,http-response']
==== 주식 주문 요청이 유효하지 않을 경우
===== 실패
operation::stock-orders/fail/invalidOrderType[snippets='http-request,http-response']

=== 주식 주문 요청 조회
==== 특정 유저의 요청 기록 조회
===== 성공
operation::stock-orders/histories/success/member[snippets='http-request,http-response']
==== 본인의 요청 기록 조회
===== 성공
operation::stock-orders/histories/success/meWithCode[snippets='http-request,http-response']

== 계좌 관련
=== 내 계좌 금액 조회
==== 성공
operation::balance/me/success[snippets='http-request,http-response']
